### ISSUE TITLE
Available  example data ？

### ISSUE THREAD

**Issue by Kai6662** [YunxiaoRen/ML-iAMR#1]
Hi YunxiaoRen，

I would like to use this tool to analyze my data. But I can't find the available example data from here. I am wondering could you create a test dataset to make us easier to use the tool. 😅😅😅😅😄😄😄  I am looking forward to your reply. Thank you.

Best regards,
Kai

**Comment by ferdoneh** [comment]
Dear Ren,
I hope you are doing well.
I am a PHD student and recently read your journal about Prediction of antimicrobial resistance based on whole-genome sequencing and machine learning.  I want to experience your results. Can you share your dataset with me? or can you help me with that?
I am looking forward to hearing from you.
Best regards,
Faranak

**Comment by YunxiaoRen** [comment]
Dear Faranak，

Thanks for interest on our paper. I am glad to share the test data and provide help. I am on the Easter holiday in these days, I will do it when I am back.

Best wishes,
Yunxiao Ren



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月15日 18:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [YunxiaoRen/ML-iAMR] Available  example data ？ (Issue #1) |

Dear Ren,
I hope you are doing well.
I am a PHD student and recently read your journal about Prediction of antimicrobial resistance based on whole-genome sequencing and machine learning. I want to experience your results. Can you share your dataset with me? or can you help me with that?
I am looking forward to hearing from you.
Best regards,
Faranak

**Comment by YunxiaoRen** [comment]
Hello,

Thanks for interest on our paper. I am glad to share the test data and provide help. I am on the Easter holiday in these days, I will do it when I am back.

Best wishes,
Yunxiao




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月14日 07:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [YunxiaoRen/ML-iAMR] Available  example data ？ (Issue #1) |

Hi YunxiaoRen，

I would like to use this tool to analyze my data. But I can't find the available example data from here. I am wondering could you create a test dataset to make us easier to use the tool. 😅😅😅😅😄😄😄 I am looking forward to your reply. Thank you.

Best regards,
Kai

**Comment by Kai6662** [comment]
Hiii Yunxiao, 

Are you Chinese? I saw some Chinese in your email. Would you like to add my Wechat  If it  would not bother you. 😀😀😀
Best，
Kai

**Comment by xiaomaofei** [comment]
您好，我是一名研究生。想体验您这边是研究结果，可是数据集找不到，具体结果实现不了。您可以发一下数据集吗？

**Comment by xiaomaofei** [comment]
Dear Yunxiao：
    Hello, I am a graduate student. I want to experience your research results, but the relevant data cases can not be found, so I can not get accurate data results. Can you send the data set here? Please

**Comment by YunxiaoRen** [comment]
> 

Hello,

Sorry for the delay in updating the example data. Now the example file is available. One file is example_data.csv, in which the rows represent samples, and the columns represent SNPs in different positions, the numbers （1,2,3,4,0） represent A, G, C, T and N. The other file is example_pheno.csv, the order of samples name is consistent with the sample name in example_data.csv, and another column is class labels.

You also can use these data to explore FCGR encoding or one-hot encoding, and then do the model training. 

Feel free to contact me if you have other questions.

Best,
Yunxiao

**Comment by YunxiaoRen** [comment]
> Dear Yunxiao： Hello, I am a graduate student. I want to experience your research results, but the relevant data cases can not be found, so I can not get accurate data results. Can you send the data set here? Please

Hello,

Sorry for the delay in updating the example data. Now the example file is available. One file is example_data.csv, in which the rows represent samples, and the columns represent SNPs in different positions, the numbers （1,2,3,4,0） represent A, G, C, T and N. The other file is example_pheno.csv, the order of samples name is consistent with the sample name in example_data.csv, and another column is class labels.

You also can use these data to explore FCGR encoding or one-hot encoding, and then do the model training.

Feel free to contact me if you have other questions.

Best,
Yunxiao

**Comment by YunxiaoRen** [comment]
> Hello,
> 
> Sorry for the delay in updating the example data. Now the example file is available. One file is example_data.csv, in which the rows represent samples, and the columns represent SNPs in different positions, the numbers （1,2,3,4,0） represent A, G, C, T and N. The other file is example_pheno.csv, the order of samples name is consistent with the sample name in example_data.csv, and another column is class labels.
> 
> You also can use these data to explore FCGR encoding or one-hot encoding, and then do the model training.
> 
> Feel free to contact me if you have other questions.
> 
> Best, Yunxiao



> Hi YunxiaoRen，
> 
> I would like to use this tool to analyze my data. But I can't find the available example data from here. I am wondering could you create a test dataset to make us easier to use the tool. 😅😅😅😅😄😄😄 I am looking forward to your reply. Thank you.
> 
> Best regards, Kai

**Comment by xiaomaofei** [comment]
Hello, please again. In the data package you gave me, I lost two NPY files running on Python software. Without these two files, I cannot achieve the effect you have achieved.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YunxiaoRen/ML-iAMR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 下午3:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YunxiaoRen/ML-iAMR] Available  example data ？ (Issue #1)





  
Hello,
 
Sorry for the delay in updating the example data. Now the example file is available. One file is example_data.csv, in which the rows represent samples, and the columns represent SNPs in different positions, the numbers （1,2,3,4,0） represent A, G, C, T and N. The other file is example_pheno.csv, the order of samples name is consistent with the sample name in example_data.csv, and another column is class labels.
 
You also can use these data to explore FCGR encoding or one-hot encoding, and then do the model training.
 
Feel free to contact me if you have other questions.
 
Best, Yunxiao
   
Hi YunxiaoRen，
 
I would like to use this tool to analyze my data. But I can't find the available example data from here. I am wondering could you create a test dataset to make us easier to use the tool. 😅😅😅😅😄😄😄 I am looking forward to your reply. Thank you.
 
Best regards, Kai

**Comment by YunxiaoRen** [comment]
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月15日 19:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [YunxiaoRen/ML-iAMR] Available  example data ？ (Issue #1) |

Hiii Yunxiao,

Are you Chinese? I saw some Chinese in your email. Would you like to add my Wechat If it would not bother you. 😀😀😀
Best，
Kai
